### ISSUE TITLE
Update Standards section on TDWG website

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/infrastructure#1]
The TDWG website currently contains two page types for the standards:
1. An overview of all standards: http://tdwgng.tdwg.org/standards/.
2. A (cover) page for each standard (e.g. http://www.tdwg.org/standards/150), with an abstract, a link to download the standard, and a (almost never used) feature to leave a comment.

The second page type is no longer needed, as all standards will be moved to GitHub, where the repository/standard can be downloaded, one can leave comments in the issue tracker and the README acts as a cover page. Each standard got a permanent URL at tdwg.org: those will remain, but will be redirected to the corresponding GitHub page (see #4).

The first page (an overview of all standards) is still useful. The question is, how do we want to present that list?
- [x] Do we group the standards in the current sections (`Current, Current (2005)`) or make one list? → one list, but we keep all status
- [x] Do we indicate `Activity`? → keep
- [x] Do we indicate `Category`? → keep for now
- [x] Do we indicate `Status`? → keep
- [x] Is it OK that the prior standards are bundled in one repository and can thus only be downloaded and commented upon as a whole? → Yes, if a prior standard becomes more important, it can get its own repo 
- [x] Do we keep this page: http://www.tdwg.org/standards/status-and-categories/ ? → yes, for now
- [x] We'll redirect the permanent URLs for the standard, but should we also do this for the prior standards? → it's just a redirect, so why not

**Comment by peterdesmet** [comment]
Updated issue body with more context.

**Comment by peterdesmet** [comment]
There was a consensus on this during exec call, so I will go ahead and do this.

**Comment by pmergen** [comment]
Ok let's see with @Stan to do it on the new website.

**Comment by peterdesmet** [comment]
Should this be done on tdwg.org or QA one (cannot remember the URL)?

**Comment by CynthiaParr-USDA** [comment]
work should all be done on tdwgng.tdwg.org -- here is what I see to do:
- [x] Merge the Current and Current 2005 lists
- [ ] Implement the redirects as summarized in https://github.com/tdwg/infrastructure/issues/4

**Comment by mdoering** [comment]
Should tdwgng.tdwg.org be up already?

**Comment by CynthiaParr-USDA** [comment]
it hasn't replaced tdwg.org yet, if that's what you mean @mdoering.

There is a list of steps to take before the cutover here: https://github.com/tdwg/infrastructure/issues/25 if you can help make sure this is a good list, we will discuss in meetings with Stan on Friday. Much of the clean up work can be done after the switch.

**Comment by mdoering** [comment]
@csparr  Ah, the site is unreachable while Im in our VPN. Something weirdly configured with the domain. All good, ignore me. I never saw the new site before, great to finally see the progress!

**Comment by peterdesmet** [comment]
The page is now one big table: http://www.tdwg.org/standards/, with broken links (because of #46). For those where we can implement redirects, we should.

**Comment by peterdesmet** [comment]
Question, should we still list the `date published` in the table on http://www.tdwg.org/standards/? Reasons not to:
1. What does `published` mean: ratified, first publication, ... ?
2. For static, migrated standards, that info is available in the README (https://github.com/tdwg/prior-standards/tree/master/economic-botany-data-collection-standard).
3. For more dynamic standards we would have to update it all the time.

If we want to indicate something, it would be the latest version number (e.g. `2009-10` or `2.06`), but even that info isn't very informative and needs to be maintained.
