### ISSUE TITLE
Migrate "Natural Collections Descriptions (NCD)"

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/infrastructure#11]
Current URL: http://www.tdwg.org/standards/312/
- [x] Contact someone from the standard task group
- [x] Verify the standard is not maintained in another repository already: there is an svn repo, which @mdoering will migrate
- [x] Decide on shortname `ncd`
- [ ] Ask for preferred citation
- [x] Create repository
- [x] Create a README based on the standard abstract
- [x] Download the standard and move the content to GitHub.
- [x] Create managing team
- [ ] Invite all relevant people to the team managing the standard on GitHub.
- [x] Describe migration in an issue
- [ ] Create a release
- [x] Document URL redirect

**Comment by mdoering** [comment]
I can take this task, Peter. I have done a lot of the technical work for NCD

**Comment by mdoering** [comment]
@peterdesmet I cannot create new teams an Owner is needed for that

**Comment by tucotuco** [comment]
You realize that NCD never made it to an accepted standard, right?

**Comment by mdoering** [comment]
Is ratification relevant, @tucotuco? I thought we simply migrate all groups no matter if they have a ratified standard or not.

**Comment by tucotuco** [comment]
In terms of migration, no, it is not relevant. It is just that the checklist makes it sound like one. No worries.

**Comment by timrobertson100** [comment]
To me it sounds correct to migrate all, perhaps indicating the status at
the top of the README or similar?
Presumably it would be released / tagged too on ratification.

**Comment by peterdesmet** [comment]
Thanks @mdoering for taking over. I have created a team `ncd`, with access to this repo and you as member. You can invite more. Ratified or not does not matter for migration, we're moving everything listed on http://www.tdwg.org/standards/. Indication of status is part of #1.

**Comment by peterdesmet** [comment]
Note, I have removed the `prior-standards` team from the `ncd` repo.

**Comment by peterdesmet** [comment]
@mdoering, where are we in migrating http://www.tdwg.org/standards/312 to https://github.com/tdwg/ncd?

**Comment by mdoering** [comment]
I havent done much yet, but ill give it another shot this weekend. With finalizing tapir

**Comment by peterdesmet** [comment]
@mdoering, any update on the migration of NCD?

**Comment by peterdesmet** [comment]
This issue can be closed. Remaining tasks (invite more collaborators, check citation and create release) will be handled by @tdwg/ncd
