### ISSUE TITLE
Migrate "ABCDDNA - DNA extension for Access to Biological Collection Data"

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/infrastructure#12]
Current URL: http://www.tdwg.org/standards/640/
- [x] Contact someone from the standard task group
- [x] Verify the standard is not maintained in another repository already
- [x] Decide on shortname: `abcd-dna`?
- [x] Ask for preferred citation
- [x] Create repository
- [x] Create a README based on the standard abstract
- [x] Download the standard and move the content to GitHub.
- [x] Create managing team
- [x] Invite all relevant people to the team managing the standard on GitHub.
- [x] Describe migration in an issue: https://github.com/tdwg/abcd-dna/issues/1
- [ ] Create a release
- [x] Document URL redirect

**Comment by peterdesmet** [comment]
@tdwg/infrastructure, who should I contact for this?

**Comment by mdoering** [comment]
Gabi Dröge from the BGBM and copy in Walter Berendsohn & Anton Güntsch

**Comment by CynthiaParr-USDA** [comment]
Can this be closed now?

**Comment by peterdesmet** [comment]
Yes, creating the release is discussed in https://github.com/tdwg/abcddna/issues/1
