### ISSUE TITLE
Migrate "Audubon Core Multimedia Resources Metadata Schema"

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/infrastructure#13]
Current URL: http://www.tdwg.org/standards/638/
- [x] Contact someone from the standard task group
- [x] Verify the standard is not maintained in another repository already: it is: https://github.com/tdwg/ac
- [x] Decide on shortname
- [x] Ask for preferred citation
- [x] Create repository
- [x] Create a README based on the standard abstract
- [x] Download the standard and move the content to GitHub.
- [x] Create managing team
- [x] Invite all relevant people to the team managing the standard on GitHub.
- [x] Describe migration in an issue
- [x] Create a release
- [x] Document URL redirect

**Comment by peterdesmet** [comment]
Dear @tdwg/audubon-core members:
1. I assume http://www.tdwg.org/standards/638/ is now https://github.com/tdwg/ac?
2. Is there anything left at http://www.tdwg.org/standards/638/ that should be moved to https://github.com/tdwg/ac?

**Comment by baskaufs** [comment]
The URL "http://www.tdwg.org/standards/638/" is supposed to be the "permanent URL" for the standard and has probably been cited multiple places as such.  Thus, if the page at that URL isn't going to be maintained, it should link or redirect to a place where a "frozen" copies of the standard are archived.  

The actual usable standards documents that are typically viewed by users are at http://terms.tdwg.org/wiki/Audubon_Core and the pages linked to that.  But my understanding is that immutable, archived copies of a standard's documents should be obtainable from the TDWG Standards repository, wherever that is.  In the past, it's been at http://www.tdwg.org/standards/638/ which is somehow magically generated from the horrid OJS system and which does NOT serve as an archive (witness the complete loss of the TAPIR standard when someone accidentally over-wrote the archived file).  I'm assuming this effort on GitHub is to replace that bad system.  

If it were up to me, I'd have http://www.tdwg.org/standards/638/ serve as a permanent, citable landing page for the standard, with a brief description of the standard, hyperlinks to the easily accessible web documents (http://terms.tdwg.org/wiki/Audubon_Core etc.), and another hyperlink to the GitHub repository that contains the documents that were "frozen" at the time the standard was adopted (i.e. the ones you get when you download http://www.tdwg.org/standards/638/download/ - download them and put them as documents in https://github.com/tdwg/ac .  Actually, I think I have the ability to do that, do you want me to?).  At this point, there is only one version of Audubon Core (the version that was adopted), but if it gets modified in the future, I'd create tags for all of the previous versions in the GitHub Repository.  

If that pattern were followed for Darwin Core, the permanent landing page would be at the standard's permanent URL http://www.tdwg.org/standards/450/ with links to the easily accessible web pages: http://rs.tdwg.org/dwc/ etc. and to the document repository with tags of all previous versions (as it already exists at https://github.com/tdwg/dwc ).

**Comment by baskaufs** [comment]
Peter, can you "watch" the Vocab repository? 
https://github.com/tdwg/vocab/watchers
At this moment, we are beginning to discuss the vocabulary management process and I see "create a managing team" in your checklist above.  That is the topic of Issue 8 https://github.com/tdwg/vocab/issues/8  How do we create a managing team???

**Comment by ramorrismorris** [comment]
I favor Steve's suggestion.

The current http://www.tdwg.org/standards/638/ is out of date as to its
"Download" link because(?) of the difficulty of editing
http://www.tdwg.org/standards.  TDWG management has been claiming that is a
situation ending real soon now.  But even if it isn't,  it is not deep to
make http://www.tdwg.org/standards/ ( or for that matter
http://www.tdwg.org/standards/638/ ) map in the DNS to some other server
with better service and use github for the actual archives.

On Sat, May 30, 2015 at 5:13 PM, Steve Baskauf notifications@github.com
wrote:

> The URL "http://www.tdwg.org/standards/638/" is supposed to be the
> "permanent URL" for the standard and has probably been cited multiple
> places as such. Thus, if the page at that URL isn't going to be maintained,
> it should link or redirect to a place where a "frozen" copies of the
> standard are archived.
> 
> The actual usable standards documents that are typically viewed by users
> are at http://terms.tdwg.org/wiki/Audubon_Core and the pages linked to
> that. But my understanding is that immutable, archived copies of a
> standard's documents should be obtainable from the TDWG Standards
> repository, wherever that is. In the past, it's been at
> http://www.tdwg.org/standards/638/ which is somehow magically generated
> from the horrid OJS system and which does NOT serve as an archive (witness
> the complete loss of the TAPIR standard when someone accidentally
> over-wrote the archived file). I'm assuming this effort on GitHub is to
> replace that bad system.
> 
> If it were up to me, I'd have http://www.tdwg.org/standards/638/ serve as
> a permanent, citable landing page for the standard, with a brief
> description of the standard, hyperlinks to the easily accessible web
> documents (http://terms.tdwg.org/wiki/Audubon_Core etc.), and another
> hyperlink to the GitHub repository that contains the documents that were
> "frozen" at the time the standard was adopted (i.e. the ones you get when
> you download http://www.tdwg.org/standards/638/download/ - download them
> and put them as documents in https://github.com/tdwg/ac . Actually, I
> think I have the ability to do that, do you want me to?). At this point,
> there is only one version of Audubon Core (the version that was adopted),
> but if it gets modified in the future, I'd create tags for all of the
> previo us versions in the GitHub Repository.
> 
> If that pattern were followed for Darwin Core, the permanent landing page
> would be at the standard's permanent URL
> http://www.tdwg.org/standards/450/ with links to the easily accessible
> web pages: http://rs.tdwg.org/dwc/ etc. and to the document repository
> with tags of all previous versions (as it already exists at
> https://github.com/tdwg/dwc ).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tdwg/tdwg.org/issues/13#issuecomment-107086539.

## 

Robert A. Morris

Emeritus Professor  of Computer Science
UMASS-Boston
100 Morrissey Blvd
Boston, MA 02125-3390

Filtered Push Project
Harvard University Herbaria
Harvard University

email: morris.bob@gmail.com
web: http://efg.cs.umb.edu/
web: http://wiki.filteredpush.org
       http://wiki.datakurator.net
       http://taxonconceptexplorer.org/
http://www.cs.umb.edu/~ram

**Comment by peterdesmet** [comment]
Hi @baskaufs, @ramorrismorris (also copying @tdwg/darwin-core).

I think there are several options for redirecting the URL http://www.tdwg.org/standards/638/:
1. Redirect to the GitHub repository, where the standard "lives". The user will find there the abstract + further links in the README (visible on the repository landing page), discussions in issues, and is able to download the standard via the button on the right or via releases.
2. Redirect to a frozen version of the standard, which is best supported with a release on GitHub (e.g. https://github.com/tdwg/dwc/releases). For Darwin Core we're actually issuing DOIs for releases.
3. Redirect to a nice landing page for the standard, different from the GitHub repository.

For Darwin Core and the other standards we migrated so far, we have decided for option 1 (though that redirect has not been implemented yet), for the reasons listed in 1 + because it's easy to do for all standards (not all of them have a website).

I would discontinue to use the somewhat arbitrarily assigned URL http://www.tdwg.org/standards/638/ as the permanent URL of the standard. Not sure which one to choose for AC instead, but specific releases can be referenced via DOI if you want (ping me in the AC repository if you want this).

So, would you be happy with the same redirect for AC (i.e. to GitHub repo), or do you prefer something else? Redirects will be handled by Apache, so they are independent from GitHub.

**Comment by peterdesmet** [comment]
Note: once we have cleared the redirect decision, we can tackle if content currently served by  http://www.tdwg.org/standards/638/ needs to be moved to the ac repository and how.

**Comment by baskaufs** [comment]
Well, I guess the question is, what do we mean when we declare a URI to be the "permanent URL" for a standard.  I would say at a minimum, it should always redirect somewhere.  http://www.tdwg.org/standards/638/ doesn't seem terribly "arbitrary" to me.  If I look at the URL (which I guess is a bad practice if you believe in opaque identifiers), it looks to me like this is the URL for a tdwg standard, which is exactly what it is.  I probably wouldn't get that from a doi or from a github.com URL.  Whatever the case, we should probably not get into the business of minting new "permanent" URLs every several years.  I suppose GitHub will be around for a while, but then I thought that was true for Google Code and it was not.  TDWG "owns" the tdwg.org domain and can keep it stable.  They don't "own" doi.org or github.com .

**Comment by mdoering** [comment]
if we could agree on the same approach for all standard repositories that would be good and make TDWG more accessible for new users. 

Personally I think it would be great to have a README driven homepage for each standard and redirect all existing "permanent" standard urls to the new github repos - approach #1.

**Comment by baskaufs** [comment]
I think approach number 1 is fine.  If it is easily implementable, we should go for it.  My main concern is that if  http://www.tdwg.org/standards/638/ has been called the "permanent URL" for the standard, then we should continue to refer to it as the permanent URL for the standard even if it ends up redirecting elsewhere.  These URLs have been cited in [1], [2], [3], and who knows where else.  I don't know why the arbitrary "638" was used, but I don't really care. Once we start telling people to use a URL to reference something, we should not change our mind a couple years later.  

I think that there is also something authoritative to having the domain of an organization in a URL.  If I see http://www.tdwg.org/standards/638/ , I assume that this is something official from tdwg.org .  If I see https://github.com/tdwg/dwc, I really don't know without further investigation.

[1] http://dx.doi.org/10.1371/journal.pone.0029715
[2] http://www.semantic-web-journal.net/content/darwin-sw-darwin-core-based-terms-expressing-biodiversity-data-rdf
[3] http://www.semantic-web-journal.net/content/lessons-learned-adapting-darwin-core-vocabulary-standard-use-rdf

**Comment by mdoering** [comment]
We could also consider to put the old, permanent tdwg URL for each standard into the top of the readme so its still very present. I dont mind keeping the old url, but I would like to start out on github as clean as we can

**Comment by jmacklin** [comment]
I agree with the logic here and we get a little bit of insurance from a
semi-non-opaque identifier as at least it points to the TDWG name space...

I also wanted to say a big thanks to all for the migration effort over the
past few days!

Best,  James

**Comment by baskaufs** [comment]
I agree with Markus - you could just say something like "Cite the URL of this standard as: [the old permanent URL].  

Yes, thanks!!!  This is real progress!

**Comment by timrobertson100** [comment]
Should we document somewhere what the expected use of the release DOI is?
e.g. http://dx.doi.org/10.5281/zenodo.12694 and those on https://github.com/tdwg/dwc/releases

I presume we do this for redundancy purposes (i.e. should GitHub disappear, there is another organization hosting a copy) but a naive user would assume the DOI was the preferred citation - or at least I would.

**Comment by ramorrismorris** [comment]
More generally, it would be good if there were a standard, prominent
mention \within/ the resource of what the preferred citation is. This is
common practice in scholarly publications, although people abuse it
routinely, not the least because the journals themselves insist on uniform
citation syntax within the bibliography.

On Mon, Jun 1, 2015 at 11:17 AM, timrobertson100 notifications@github.com
wrote:

> Should we document somewhere what the expected use of the release DOI is?
> e.g. http://dx.doi.org/10.5281/zenodo.12694 and those on
> https://github.com/tdwg/dwc/releases
> 
> I presume we do this for redundancy purposes (i.e. should GitHub
> disappear, there is another organization hosting a copy) but a naive user
> would assume the DOI was the preferred citation - or at least I would.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tdwg/tdwg.org/issues/13#issuecomment-107574559.

## 

Robert A. Morris

Emeritus Professor  of Computer Science
UMASS-Boston
100 Morrissey Blvd
Boston, MA 02125-3390

Filtered Push Project
Harvard University Herbaria
Harvard University

email: morris.bob@gmail.com
web: http://efg.cs.umb.edu/
web: http://wiki.filteredpush.org
       http://wiki.datakurator.net
       http://taxonconceptexplorer.org/
http://www.cs.umb.edu/~ram

**Comment by peterdesmet** [comment]
Thanks all for the input. I take away, for standards in general:
- Permanent URL is maintained by TDWG
- Permanent URL should redirect to GitHub repository
- Permanent URL should be listed clearly in README
- Preferred citation (with permanent URL) should be mentioned in README

Correct?

If so, I'd like to document these guidelines somewhere. Probably best at vocab??

**Comment by peterdesmet** [comment]
For AC in specific:
- http://www.tdwg.org/standards/638/ should redirect to https://github.com/tdwg/ac
- Should the content at http://www.tdwg.org/standards/638/download/ (not final version yet) be moved to ac repo or is this already the case?
- Do you want to copy something from the abstract at http://www.tdwg.org/standards/638/ ?

**Comment by baskaufs** [comment]
I don't see anything in the AC repo except a folder called "wiki".  So I think the content needs to be moved.  

I can document the guidelines in vocab.  But since they don't really have any force other than a suggestion at this point, I think that if you implement them consistently that would set a good precedent.

**Comment by baskaufs** [comment]
Created this document:
https://github.com/tdwg/vocab/blob/master/standards-permanent-url.md

**Comment by ramorrismorris** [comment]
On Tue, Jun 2, 2015 at 10:39 AM, Steve Baskauf notifications@github.com
wrote:

> I don't see anything in the AC repo except a folder called "wiki". So I
> think the content needs to be moved.
> 
> By "content" do you mean the content of what is in  the zip file referenced
> in http://www.tdwg.org/standards/638/download/ ?
> 
> I can document the guidelines in vocab. But since they don't really have
> any force other than a suggestion at this point, I think that if you
> implement them consistently that would set a good precedent.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tdwg/infrastructure/issues/13#issuecomment-107976020.

## 

Robert A. Morris

Emeritus Professor  of Computer Science
UMASS-Boston
100 Morrissey Blvd
Boston, MA 02125-3390

Filtered Push Project
Harvard University Herbaria
Harvard University

email: morris.bob@gmail.com
web: http://efg.cs.umb.edu/
web: http://wiki.filteredpush.org
       http://wiki.datakurator.net
       http://taxonconceptexplorer.org/
http://www.cs.umb.edu/~ram

**Comment by peterdesmet** [comment]
@ramorrismorris Yes, content of zip.

@baskaufs I just created this document in infrastructure: https://github.com/tdwg/infrastructure/blob/master/migration/guidelines-for-standard-repositories.md, which expands on your document. I don't mind in which repo to keep it, but best to have only one.

**Comment by baskaufs** [comment]
Yes

Bob Morris wrote:

> On Tue, Jun 2, 2015 at 10:39 AM, Steve Baskauf notifications@github.com
> wrote:
> 
> > I don't see anything in the AC repo except a folder called "wiki". So I
> > think the content needs to be moved.
> > 
> > By "content" do you mean the content of what is in the zip file referenced
> > in http://www.tdwg.org/standards/638/download/ ?
> > 
> > I can document the guidelines in vocab. But since they don't really have
> > any force other than a suggestion at this point, I think that if you
> > implement them consistently that would set a good precedent.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/tdwg/infrastructure/issues/13#issuecomment-107976020.
> 
> ## 
> 
> Robert A. Morris
> 
> Emeritus Professor of Computer Science
> UMASS-Boston
> 100 Morrissey Blvd
> Boston, MA 02125-3390
> 
> Filtered Push Project
> Harvard University Herbaria
> Harvard University
> 
> email: morris.bob@gmail.com
> web: http://efg.cs.umb.edu/
> web: http://wiki.filteredpush.org
> http://wiki.datakurator.net
> http://taxonconceptexplorer.org/
> http://www.cs.umb.edu/~ram
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/tdwg/infrastructure/issues/13#issuecomment-107985090.

## 

Steven J. Baskauf, Ph.D., Senior Lecturer
Vanderbilt University Dept. of Biological Sciences

postal mail address:
PMB 351634
Nashville, TN  37235-1634,  U.S.A.

delivery address:
2125 Stevenson Center
1161 21st Ave., S.
Nashville, TN 37235

office: 2128 Stevenson Center
phone: (615) 343-4582,  fax: (615) 322-4942
If you fax, please phone or email so that I will know to look for it.
http://bioimages.vanderbilt.edu
http://vanderbilt.edu/trees

**Comment by baskaufs** [comment]
@peterdesmet Maybe it would be best to take the permanent URL recommendations and add them to your document and I will get rid of mine.  The scope of the vocab TG is to write a standard for vocab management and I think these guidelines are implementation details that won't be put in the standard.  After you add the points to your document, I'll delete mine and then make a reference to it in the issue that is open on the subject.  does that sound OK?

**Comment by peterdesmet** [comment]
@baskaufs, I've updated [my document](https://github.com/tdwg/infrastructure/blob/master/migration/guidelines-for-standard-repositories.md), so you can go ahead.

**Comment by peterdesmet** [comment]
Regarding the content at http://www.tdwg.org/standards/638/, just like for `vocab`, I've created a branch on `ac` and described it in this issue: https://github.com/tdwg/ac/issues/91

**Comment by baskaufs** [comment]
My redundant document has been deleted and I've referenced [your document](https://github.com/tdwg/infrastructure/blob/master/migration/guidelines-for-standard-repositories.md) in the [vocab issue 9](https://github.com/tdwg/vocab/issues/9).
