### ISSUE TITLE
Can I rename the GitHub teams audubon-core and darwin-core

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/infrastructure#14]
Each time I move a standard to Github, I create a specific GitHub team to manage the standard (with admin access). I'd like to be consistent in naming these teams. So far I have ([full list](https://github.com/orgs/tdwg/teams)):

```
team | repo
@owners | all
@conferences | conferences
@exec | exec
@infrastructure | tdwg.org
@prior-standards | prior-standards
@audubon-core  | ac
@darwin-core | dwc
@guid | guid-as
@ncd | ncd
@vocab | vocab
```

Does anyone have an objection if rename the `audubon-core` team to `ac` and `darwin-core` to `dwc` so they can be @mention ed as such?

/cc @tdwg/exec @tdwg/audubon-core @tdwg/darwin-core (this is an example of how you can ping specific teams)

**Comment by ramorrismorris** [comment]
Seems ok to me

On Sun, May 31, 2015 at 11:15 AM, Peter Desmet notifications@github.com
wrote:

> Each time I move a standard to Github, I create a specific GitHub team to
> manage the standard (with admin access). I'd like to be consistent in
> naming these teams. So far I have (full list
> https://github.com/orgs/tdwg/teams):
> 
> team | repo
> @owners | all
> @conferences | conferences
> @exec | exec
> @infrastructure | tdwg.org
> @prior-standards | prior-standards
> @audubon-core  | ac
> @darwin-core | dwc
> @guid | guid-as
> @ncd | ncd
> @vocab | vocab
> 
> Does anyone have an objection if rename the audubon-core team to ac and
> darwin-core to dwc so they can be @mention https://github.com/blog/821
> ed as such?
> 
> /cc @tdwg/exec https://github.com/orgs/tdwg/teams/exec
> @tdwg/audubon-core https://github.com/orgs/tdwg/teams/audubon-core
> @tdwg/darwin-core https://github.com/orgs/tdwg/teams/darwin-core (this
> is an example of how you can ping specific teams)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tdwg/tdwg.org/issues/14.

## 

Robert A. Morris

Emeritus Professor  of Computer Science
UMASS-Boston
100 Morrissey Blvd
Boston, MA 02125-3390

Filtered Push Project
Harvard University Herbaria
Harvard University

email: morris.bob@gmail.com
web: http://efg.cs.umb.edu/
web: http://wiki.filteredpush.org
       http://wiki.datakurator.net
       http://taxonconceptexplorer.org/
http://www.cs.umb.edu/~ram

**Comment by tucotuco** [comment]
Good idea.

**Comment by peterdesmet** [comment]
Thanks, it's done: https://github.com/orgs/tdwg/teams
