### ISSUE TITLE
Should we expand the scope of this repository?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/infrastructure#15]
Should we expand the scope of this repository from stuff related to the tdwg.org website only, to all TDWG infrastructure? I personally think that's already the case.

If so, can I'll this repository from `tdwg.org` to `infrastructure`. This is also the name of the team managing this repo. GitHub will redirect all old links automatically.

**Comment by mdoering** [comment]
I support that. http://rs.tdwg.org should be covered here too

**Comment by CynthiaParr-USDA** [comment]
I agree.  I saw that the team of people was already called "infrastructure".

**Comment by peterdesmet** [comment]
Ok, do I need to wait for more votes or go ahead?

**Comment by jmacklin** [comment]
I agree as well!

JAmes

**Comment by dkoureas** [comment]
+1

Kind regards,
Dimitris

**Comment by peterdesmet** [comment]
Done.

**Comment by sblum** [comment]
+1 from me, too.

I share Steve's sensibility that it would be good to maintain the permanent URL, but that might commit us to maintaining mod-rewrite on (or in front of) www.tdwg.org.  I think it would have been simpler if rs.tdwg.org had "responsibility" for serving all TDWG permanent resources, but it seems too late for that as some number of standards have been published with a permanent URL of www.tdwg.org/standards/[###], so www will have to be split.  I'll look into what Typo3 can do in managing URLs.

-Stan
