### ISSUE TITLE
What to do with wiki content?

### ISSUE THREAD

**Issue by mdoering** [tdwg/infrastructure#16]
Should we migrate TAPIR wiki pages to the [TAPIR wiki](https://github.com/tdwg/tapir/wiki)?
http://wiki.tdwg.org/twiki/bin/view/TAPIR/

What to do with the pdf based reports here:
http://www.tdwg.org/activities/tapir/

**Comment by CynthiaParr-USDA** [comment]
In this case (and the others associated with standards), the TAPIR wiki should be moved to the GitHub TAPIR wiki

Stan says the PDF based reports can stay where they are as they are associated with the TAPIR activity page is already migrated to the new Typo3 site.

**Comment by CynthiaParr-USDA** [comment]
As far as the overall twiki content, it already migrated to another virtual server, 106. Should it be eventually be moved to the media wikifarm? Probably yes for that content not handled by GitHub wikis.

Probably not urgent right now.

**Comment by mdoering** [comment]
Created issue to migrate TAPIR wiki content: https://github.com/tdwg/tapir/issues/3

**Comment by mdoering** [comment]
What should happen to the old wiki.tdwg.org content (apart from TAPIR)?
The site does not seem to be active anymore: http://wiki.tdwg.org/

current virtual host definition: https://github.com/tdwg/infrastructure/blob/master/vhosts/wiki.tdwg.org.conf

**Comment by mdoering** [comment]
I would favor migrating wiki content to github as much as possible instead of running a tdwg wiki server.
Alternatively http://biowikifarm.net/ could host the content

**Comment by timrobertson100** [comment]
@mdoering wrote

> I would favor migrating wiki content to github as much as possible instead of running a tdwg wiki server.

+1

**Comment by baskaufs** [comment]
Unless the old TDWG wiki is going to be resurrected and actually used as a wiki, I would just dump it somewhere on GitHub.  From my perspective, I think it needs to be citable.  For example, there is a lot of stuff related to the development of the TDWG infrastructure that was recorded in the Wiki (e.g. TAG reports) that should inform future work.  That stuff has now gone dark, and shouldn't.

**Comment by peterdesmet** [comment]
Ok, if we host it on GitHub, should we:
- Host it in a GitHub repository or associated wiki?
- Move the standard-related wikis to their corresponding GitHub repo (or wiki) or keep all of it together?

**Comment by baskaufs** [comment]
It seems like it would make sense to move the wikis to the corresponding GitHub repo if there is one.  I think a lot of the wikis don't have a lot of content, but the ones that I've spent the most time reading are things associated with the TAG and the development of the TDWG ontology, which at the time was supposed to be a critical component of the TDWG infrastructure.  So if there is going to be a TAG repo, some of that stuff could go there.  But I'm not clear about whether the TAG is actually going to have a role in standards maintenance and development in the future.

**Comment by peterdesmet** [comment]
The following wiki sections could be placed in their corresponding repo on GitHub:

| Wiki | GitHub repository |
| --- | --- |
| http://wiki.tdwg.org/TAPIR/ | https://github.com/tdwg/tapir (will be migrated, see https://github.com/tdwg/tapir/issues/3) |
| http://wiki.tdwg.org/twiki/bin/view/DarwinCore & http://wiki.tdwg.org/DarwinCore/ (deprecated) | https://github.com/tdwg/dwc |
| http://wiki.tdwg.org/ABCD/ | https://github.com/tdwg/abcd |
| http://wiki.tdwg.org/GUID/ | https://github.com/tdwg/guid-as |
| http://wiki.tdwg.org/NCD/ | https://github.com/tdwg/ncd |
| http://wiki.tdwg.org/twiki/bin/view/SDD & http://wiki.tdwg.org/BDI/ ? | https://github.com/tdwg/sdd |
| http://wiki.tdwg.org/TNC/ | https://github.com/tdwg/tcs ? |
| http://wiki.tdwg.org/TIP/ | https://github.com/tdwg/infrastructure |
| http://wiki.tdwg.org/Executive/ | https://github.com/tdwg/exec |
| http://wiki.tdwg.org/Conferences/ & http://wiki.tdwg.org/ProgramCommittee/ & http://wiki.tdwg.org/LocalCommittee/ | https://github.com/tdwg/conferences |

But I'm wondering if this won't clutter the repositories/associated wikis? Maybe we should move everything to one GitHub wiki first, as an archive. Then contact all the relevant groups if they want to continue using the wiki as a collaborative platform, at which point it can be moved to the corresponding repo?

**Comment by mdoering** [comment]
+1 for first archiving the entire wiki somewhere. We need to do this in order to switch off servers in a reasonable time

**Comment by baskaufs** [comment]
i agree about the reasonable amount of time.  my main concern is generating a trail of links the stop working. As long as the entire wiki stays at the new location permanently, I don't see why groups could not copy old posts to start a new wiki if they wanted to. But I doubt that many would.

---

Steven J. Baskauf, Ph.D.
Vanderbilt Dept. of Biological Sciences

**Comment by mdoering** [comment]
Maybe it is possible to crawl the old wiki and keep it as static html files in github so we can setup redirects from the old domain?

**Comment by peterdesmet** [comment]
@mdoering if we can replicate the wiki directory structure on GitHub, we'd only have to redirect `http://wiki.tdwg.org/twiki/`. We'd then still have several option on how to host it on GitHub:
- In the repository: redirect to https://github.com/tdwg/wiki-archive/tree/master/
- In the wiki: redirect to https://github.com/tdwg/wiki-archive/wiki
- As a static site: redirect to http://tdwg.github.io/wiki-archive

But the advantage of the last option (your suggestion) is that it can look like the old wiki + since it's in a branch, one could update the repository without affecting the hosted archive.

@baskaufs I agree that it's probably best to host the entire wiki somewhere as an archive (here: https://github.com/tdwg/wiki-archive/wiki) and **copy** parts of it to specific repositories if the contributors of those repositories are interested.

**Comment by peterdesmet** [comment]
@mdoering instead of crawling, who has direct access to the (old) server where the wiki is hosted? @sblum? @acheccuc?

**Comment by sblum** [comment]
The twiki was the first piece of the infrastructure to start causing problems (several years ago), so someone at GBIF (I think) was able to migrate the content from old one to a newer one on 192.38.28.106 (owl).  (My TDWG login stopped working after that.)  Owl is the same server that Mailman is currently running on.  I don't think it's accepting ssh connections from outside the GBIF network, though.  I can't login from outside (it times out).  I have to login to the tdwgng server first and from there go to owl.  @mdoering, you do have an rsa key on owl.

**Comment by CynthiaParr-USDA** [comment]
From Dec check-in discussion with Peter

Aim to shut down this server by end of January

New ticket for action to be created. https://github.com/tdwg/infrastructure/issues/62

**Comment by CynthiaParr-USDA** [comment]
FYI there seems to be good wiki content in the Wayback Machine should we need to shut down the old server ASAP. E.g. from Dec 2013 https://web.archive.org/web/20131211055120/http://www.tdwg.org/

**Comment by mdoering** [comment]
I have copied all wiki content into a new repository so the content is safe for sure:
https://github.com/tdwg/wiki-archive

The actual versioned data appears to be here: https://github.com/tdwg/wiki-archive/tree/master/twiki/data with attachments here: https://github.com/tdwg/wiki-archive/tree/master/twiki/pub

**Comment by stanblum** [comment]
Thanks for that Markus!  I've been going through stuff on the admin pages, where Lee had left a lot of notes.  I confirm that the content is very easily readable from there (not formatted, but readable).  I think that makes the content recoverable for any future need, though some work would be required to make it look nice.  I think we are now at the point of needing to contact conveners of groups with old wiki content and direct them to the new location(s).  #62

**Comment by CynthiaParr-USDA** [comment]
As there is another ticket for contacting the conveners, I am closing this now.

**Comment by mdoering** [comment]
I have tried to redirect wiki pages to their github archive text versions

**Comment by mdoering** [comment]
seems to work: http://wiki.tdwg.org/twiki/bin/view/GUID/LSIDServicesDiscussion
