### ISSUE TITLE
Migrate "GUID and Life Sciences Identifiers Applicability Statements" to GitHub

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/infrastructure#2]
Current URL: http://www.tdwg.org/standards/150/
- [x] Contact someone from the standard task group
- [x] Verify the standard is not maintained in another repository already
- [x] Decide on shortname: `guid-as`
- [x] Ask for preferred citation
- [x] Create repository
- [x] Create a README based on the standard abstract
- [x] Download the standard and move the content to GitHub.
- [x] Create managing team
- [ ] Invite all relevant people to the team managing the standard on GitHub.
- [x] Describe migration in an issue
- [x] Create a release
- [x] Document URL redirect

**Comment by CynthiaParr-USDA** [comment]
The primary name on the task group was Kevin Richards, Email: richardsk777@gmail.com 
but I'm sure that there were others involved.  I think the suggested name is fine.  I think it would be good to start the README with the basic metadata, move the content to GitHub then get Richards or someone else he designates to review things prior to the formal release.

**Comment by peterdesmet** [comment]
Contacted Kevin.

**Comment by CynthiaParr-USDA** [comment]
Peter, any word from Kevin? If we need a new champion let us know.

**Comment by peterdesmet** [comment]
Yes, I know everything. Just need to find the time to do it. You can keep this assigned to me.

**Comment by peterdesmet** [comment]
Most of the work done. Standard now lives at https://github.com/tdwg/guid-as and can be removed from TDWG website. Will close this issue once final tasks have been resolved.

**Comment by CynthiaParr-USDA** [comment]
Also there is some content on the DAV server as described here
https://github.com/tdwg/infrastructure/issues/21

**Comment by peterdesmet** [comment]
Release created at https://github.com/tdwg/guid-as/releases/tag/2010-09, still need to find team members.
