### ISSUE TITLE
Determine fate of TAPIR content on www.tdwg.org/dav

### ISSUE THREAD

**Issue by CynthiaParr-USDA** [tdwg/infrastructure#22]
http://www.tdwg.org/dav/subgroups/tapir/

**Comment by mdoering** [comment]
If I am right all the TAPIR DAV content is another view on the subversion repo which has been copied to the new tapir github repo already. In particular the specs are at https://github.com/tdwg/tapir/tree/master/docs

We just need to decide how to best expose them as the html is not rendered fine in raw mode.
But similar to dwc tapir has urls to be maintained under rs.tdwg.org: http://rs.tdwg.org/tapir/
