### ISSUE TITLE
Resolve last few Infield issues

### ISSUE THREAD

**Issue by CynthiaParr-USDA** [tdwg/infrastructure#25]
- [x] new user registration (talked to cip)
- [x] last of user payments via PayPal (charged but didn’t report back)
- [ ] MailChimp plugin supposedly has a manual trigger to push all new users into mailchimp, deletes dead address from Typo3 registry
- [x] figure out how to do news on the new site
- [x] enable the lost password functions

**Comment by CynthiaParr-USDA** [comment]
Stan talked to Catherine about the first three of these.  There's a news extension but we don't see how it works yet.

**Comment by CynthiaParr-USDA** [comment]
Stan, we need an update on this ticket...

**Comment by CynthiaParr-USDA** [comment]
stan says payments should be working. I will test.

**Comment by sblum** [comment]
- Individual membership payments work and are now showing on the membership reporting page.  **I need a volunteer to test the payment an institutional membership through PayPal** (with a credit card).  
- Email from the server is now working.  Dependent functions (now working) include:  forgot password;  newly registered user can confirm email and become regular_user.  (We are **not** requiring that newly registered users get reviewed by a secretariat member; they now become regular_users as soon as they confirm their email address.
- News items can be added by backend admins using a form that exists there.  (To keep costs down, I deferred fixing the form we had that can be accessed by regular users to submit news items. It wasn't used that often. I propose instead that all news items get submitted to and entered by the secretariat.)

Remaining steps before cut-over:
- [ ] Review / revise this list of steps  
- [ ] create list of tests to check successful operation (critical functions)
- [ ] Confirm DNS control with Cip (GBIF admins), reduce TTL in advance of switch
- [ ] Freeze edits on conference page; migrate conference content
- [ ] Execute switch ( www --> tdwgpg; tdwgng --> www )

**Comment by pmergen** [comment]
Hi
For the institution would suggest GBIF. Andrea hahn had recently contacted us.
Pat

**Comment by CynthiaParr-USDA** [comment]
Chuck said that he tested the institutional payment.

**Comment by CynthiaParr-USDA** [comment]
The only thing here supposedly undone is the MailChimp push. If that is still an issue, please create a new ticket.
