### ISSUE TITLE
Can we redirect URLs?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/infrastructure#3]
One of the tasks in migrating the TDWG standards to GitHub is redirecting the what is called "permanent URL" of the standard (such as http://www.tdwg.org/standards/450) to the GitHub repository of the standard. We already have the OK from the task groups to redirect this URL for Darwin Core, [Vocab](https://github.com/tdwg/vocab/issues/1#issuecomment-101322778) and GUID applicability statement (though I still have to migrate that one) and the prior standards (which we could redirect to a subdirectory of https://github.com/tdwg/prior-standards).

Does anyone know how to redirect on Typo3?

**Comment by sblum** [comment]
I'm not sure we want to link www.tdwg.org/standards/450 to the GitHub repository.  I think the old practice was to link that URL to the "cover page" for the standard.  On the cover page there should be a link to "download" the standard, and maybe a place to view it online, such as http://rs.tdwg.org/dwc/index.htm.  Does GitHub allow us to alias repositories on their site with a client's URL, like http://rs.tdwg.org/dwc/index.htm.  If not, then I think we have two choices:  1) accept the GitHub URL, or pull the content over to a TDWG server where we can manage the URLs.  

I've made some progress getting Typo3 to name the standards cover page as the old number, but I'm getting some odd behavior from the link target (opening new tab/page regardless of how I change the setting).  I'm calling this out to the contractor tomorrow.

**Comment by peterdesmet** [comment]
@sblum, a GitHub repository (e.g. https://github.com/tdwg/dwc) acts the same way as a cover page in my opinion:
- The README gives/should give an introduction to the standard (the README text is displayed by default for each repository on GitHub)
- You can download the whole repository on the right hand side (`download zip`)
- Any relevant external website can be mentioned in the README

Alternatively/in addition, each repository can be made into its own website, e.g. http://tdwg.github.io/dwc/terms/index.htm (a working example), the URL of which consists of three things:
- `http://tdwg.github.io`: Default option, can be replaced with a custom domain. Choosing `www.tdwg.org` as a custom domain would be tricky though, as that main website is maintained outside GitHub.
- `/dwc`: the name of the repository. This part of the URL can only be changed by renaming the repository
- `/terms/index.htm`: A directory and file in that repository. This part of the URL can only be changed by renaming the directory and file.

I would refrain from creating those websites for now and choose to maintain the standard in one place, on GitHub, by the task group and only reference the repository, using a redirect.

**Comment by CynthiaParr-USDA** [comment]
Tim proposes rewrite rules on the TDWG GBIF server.

**Comment by timrobertson100** [comment]
We believe there are around 20 URLs that need to be rewritten only.
The simplest solution will be to put something like an `Apache  mod_rewrite` in front of the TDWG site for those URLs.  When the site is moved, please contact trobertson@gbif.org and admin@gbif.org and we will make this happen.

**Comment by mdoering** [comment]
We also need redirects for the changed dwc layout: https://github.com/tdwg/dwc/issues/80 under rs.tdwg.org
In general I would prefer redirects over rewrites so users are aware of the change

**Comment by timrobertson100** [comment]
Indeed, it would issue `301 moved permanently` to the new location

**Comment by peterdesmet** [comment]
Great. I'll add a list of URLs to be redirected to this repository.
