### ISSUE TITLE
Decide on format for preferred citation for standards

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/infrastructure#32]
As outlined in [this guidelines document](https://github.com/tdwg/infrastructure/blob/master/migration/guidelines-for-standard-repositories.md), we will add a preferred citation for each standard in the README. The preferred citation (with updated release number and year) can also be listed for each release. This citation should at least include:
- permanent URL
- name of the standard

and preferably:
- authors
- year
- release/version number
- indication of "draft standard" (for 0.x releases)

and maybe:
- task group?
- accessed date?
- mention of TWDG? (although you can see that from the permanent URL: http://www.tdwg.org/standards/id)

It would be convenient if we can decide on a **standard format** for this preferred citation, which I can then include in the guidelines document and which I'll add to every README and release on GitHub.
## My suggestion

> Last name First name`,` Last name First name`.` year`.` Full name of the standard + `(draft standard`) if applicable`,` `Version` releasenumber or date`. Biodiversity Information Standards (TDWG)` http://www.tdwg.org/standards/id (no trailing slash)

For example:

> Wieczorek John, Döring Markus, De Giovanni Renato, Robertson Tim, Vieglais Dave, Desmet Peter. 2014. Darwin Core, Version 2014-11-08. Biodiversity Information Standards (TDWG) http://www.tdwg.org/standards/450

New versions can have more authors.
## Other suggestions

By @baskaufs in [this comment](https://github.com/tdwg/vocab/issues/10#issuecomment-108100552):

> Hyam, Roger. 2007. TDWG Standards Documentation Specification (draft standard). TDWG Infrastructure Project. 2007-11-05 version. http://www.tdwg.org/standards/147

By @ramorrismorris in [this comment](https://github.com/tdwg/ac/issues/91#issuecomment-108171657):

> Morris, Robert A., et al., 2014. Audubon Core Multimedia Resources Metadata Schema, Release 1.0, http://www.tdwg.org/standards/638/

Currently listed for [Darwin Core](https://github.com/tdwg/dwc/blob/master/README.md#how-to-attribute-and-cite-darwin-core):

> Darwin Core Task Group, Biodiversity Information Standards (TDWG). 2009. Darwin Core. 
> http://rs.tdwg.org/dwc/ (accessed on 2014-10-31).

Listed in a [Darwin Core release](http://zenodo.org/record/12694#.VW6kkFyqqko):

> Wieczorek, John et al. (2014). Darwin Core: 2014-11-08. Zenodo. 10.5281/zenodo.12694

Suggested for [LSID applicability statement](https://github.com/tdwg/guid-as/blob/master/README.md#lsid-applicability-statement):

> TDWG Life Sciences Identifiers (LSID) Applicability Statement, TDWG Draft Standard, TDWG Globally Unique Identifiers Task Group (Ricardo Pereira, Kevin Richards, Donald Hobern, Roger Hyam, Lee Belbin, Stan Blum), Sept 2009, http://www.tdwg.org/standards/150

Please comment on how we should format this, including punctuation (e.g. between names and for year).

/cc @tdwg/exec

**Comment by peterdesmet** [comment]
Blocks:
- https://github.com/tdwg/infrastructure/issues/10 / https://github.com/tdwg/vocab/issues/10
- https://github.com/tdwg/infrastructure/issues/12 / https://github.com/tdwg/abcd-dna/issues/1
- https://github.com/tdwg/infrastructure/issues/13 / https://github.com/tdwg/ac/issues/91
- https://github.com/tdwg/infrastructure/issues/5
- https://github.com/tdwg/infrastructure/issues/6

Affects:
- https://github.com/tdwg/infrastructure/issues/2
- https://github.com/tdwg/infrastructure/issues/7
- https://github.com/tdwg/infrastructure/issues/8
- https://github.com/tdwg/infrastructure/issues/9
- https://github.com/tdwg/infrastructure/issues/11
- All prior standards: https://github.com/tdwg/prior-standards

**Comment by pmergen** [comment]
Hi 
I would be in favor of a citation format where TDWG is of course mentioned, but also the names of the co-authors (but as those may vary in time, has to keep updated). 
Walso need some flexibility as some journals have standard citation formats rules. 

in some cases additional to the citation only, you may have to add a request to acknowledge other contributing institutions or funding bodies (who request this in many cases)

More generally you may want to add some information on using the logo(s) and in which context.

**Comment by CynthiaParr-USDA** [comment]
Suggestion: use Biodiversity Information Standards (TDWG) as the publisher.

Provide a bibtex formatted text file.

**Comment by CynthiaParr-USDA** [comment]
Need to resolve in the next few days.

**Comment by peterdesmet** [comment]
Deadline: July 2

**Comment by pmergen** [comment]
Hi
For online content citations date accessed is a standard request from many journals and others. Would thus recommend we suggest to have it as it is a best practice advise.

**Comment by peterdesmet** [comment]
Since the citation indicates the release date, a `date accessed` doesn't provide much more information, so I would not include this.

**Comment by pmergen** [comment]
yes that is what I meant not to put in in the citation example.

but if room, indicated that some journals request it in an additional sentence  . but that is my "helpdesk" side.

**Comment by peterdesmet** [comment]
I see. :smile: As discussed in the call, it's a preferred citation. A journal will probably have other requirements regarding the format, but at least we indicate what we would like to have in there.

**Comment by dkoureas** [comment]
@peterdesmet  Following today's XC meeting, please find below an example bib record for the Darwin Core Standard. I set the reference type to 'misc' as no other type seems to match for referencing a Standard. I also chose to add the release date to the 'edition' field. Any reference manager software can parse this and deliver a citation format according to any common format. 

@misc {DarwinCore2014,
    title = {Darwin Core},
    year = {2014},
    publisher = {Biodiversity Information Standards (TDWG)},
    edition = {Release 2014-11-08},
    url = {http://www.tdwg.org/standards/450},
    author = {Wieczorek, John and D{\"o}ring, Markus and De Giovanni, Renato and Robertson, Tim and Vieglais, Dave and Desmet, Peter}
}

**Comment by baskaufs** [comment]
Reference: [Recommended practices for citation of data published through the GBIF network](http://www.gbif.org/resource/80761)

**Comment by CynthiaParr-USDA** [comment]
Is there anything left to do on this @peterdesmet ?

**Comment by AaronWilton** [comment]
Sorry to have missed the conversations in the meeting(s), so hope this doesn't re-open/duplicate debate.

The initial question was around a preferred citation format, but that now seems to have translated into the preferred fields that should be included in the bibliographic information.  Was discussion still given to providing a recommended citation format so there is consistency across TDWG standards? (I still see some value in this). 

If yes, then the format of the author string seems rather non-standard for a citation (appropriate for content).  It is more typical for multiple authors to be separated by semi-colons or commas in a citation.

**Comment by peterdesmet** [comment]
I'd like to close this discussion. To keep things simple, I'll add `Biodiversity Information Standards (TDWG)` as a publisher to the preferred citation. The preferred citation will be indicated as a blockquote at the end of the README file of a standard, but I will not add a bibtex to the repository (because then we need to maintain two files). So, an example of a preferred citation is:

> Wieczorek John, Döring Markus, De Giovanni Renato, Robertson Tim, Vieglais Dave, Desmet Peter. 2014. Darwin Core, Version 2014-11-08. Biodiversity Information Standards (TDWG) http://www.tdwg.org/standards/450

And if the authors are not readily known, I'll use the task group as the author (can be updated later):

> Access to Biological Collections Data task group. 2007. Access to Biological Collection Data (ABCD), Version 2.06. Biodiversity Information Standards (TDWG) http://www.tdwg.org/standards/115

**Comment by peterdesmet** [comment]
Updated to use the word `version` instead of `release` (as suggested by @timrobertson100)
