### ISSUE TITLE
 Genomic Biodiversity Working Group GBWG on New TDWG Website

### ISSUE THREAD

**Issue by pmergen** [tdwg/infrastructure#38]
This group was not on the former TDWG website and needs to be created on the new one. 
The charter text was approved. We need this text and see if it needs some updates and upload it to the new website ? 
this seems to be the latest version I found : https://docs.google.com/document/d/1KI1cZ8Onw6Kq0nY5suTWtNo5occQ7ON0kc6N0AUrZMI/edit?hl=en_US
Need help to review and confirm that this is the text to go online ?
Pat

**Comment by pmergen** [comment]
John Deck and Ramona Walls have revised text in google doc. has to be created as a new entry in activities on the TDWG site

**Comment by CynthiaParr-USDA** [comment]
I started to make the new page but have not finished it. Waiting to hear from Stan how the process is supposed to go.
- [x] Finish page with charter
- [x] Add to activities page

**Comment by stanblum** [comment]
This was finished on Aug 7, 2015.  I should have closed it then.
