### ISSUE TITLE
Species Information Interest Group

### ISSUE THREAD

**Issue by CynthiaParr-USDA** [tdwg/infrastructure#39]
- [x] Create folder of pages from the sample
- [x] Modify titles etc. for this IG
- [x] Set up charter page
- [x] Make the page public
- [x] Make sure that convener has access to make changes
- [x] Add to the Activities summary table

**Comment by csparr** [comment]
- [x] Create folder of pages from the sample
- [ ] Modify titles etc. for this IG
- [ ] Set up charter page
- [ ] Make the page public
- [ ] Make sure that convener has access to make changes
- [ ] Add to the Activities summary table

**Comment by stanblum** [comment]
This has been up for a while.  And I've just checked - Paco has rights to edit the web site.  I'll send him a note alerting him to that fact and to ask for help if he needs it.  (I think he's on vacation at the moment.)  I think this task is done.

**Comment by CynthiaParr-USDA** [comment]
Thanks -- I didn't see it because I assumed it started with S where it is starting with T.  Any particular reason it starts with TDWG?

**Comment by stanblum** [comment]
Somewhere I was given the abbreviation TSI -- TDWG Species Information.  But you're right, it should be Species Information (and it is in the navigation tree where characters are at a premium).  That would mandate changing name abbreviation to SIIG or ??   I'll ask Paco.
