### ISSUE TITLE
Migrate "TAPIR - TDWG Access Protocol for Information Retrieval"

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/infrastructure#5]
Current URL: http://www.tdwg.org/standards/449/
- [x] Contact someone from the standard task group
- [x] Verify the standard is not maintained in another repository already
- [x] Decide on shortname: `tapir`
- [x] Ask for preferred citation
- [x] Create repository
- [x] Create a README based on the standard abstract
- [x] Download the standard and move the content to GitHub.
- [x] Create managing team
- [x] Invite all relevant people to the team managing the standard on GitHub.
- [x] Describe migration in an issue: not required
- [x] Create a release: https://github.com/tdwg/tapir/releases/tag/1.0
- [x] Document URL redirect

**Comment by peterdesmet** [comment]
@tdwg/infrastructure, who should I contact for this?

**Comment by mdoering** [comment]
I'm happy to take this on. There are quite a bit of files to keep online. Especially the alias and output model files hosted here: http://rs.tdwg.org/tapir/
Those URLs need to be redirected as live tapir instance rely on them

**Comment by mdoering** [comment]
Those URLs need to be redirected as live tapir instance rely on them

**Comment by CynthiaParr-USDA** [comment]
There is also content on the dav server
https://github.com/tdwg/infrastructure/issues/22

**Comment by peterdesmet** [comment]
@mdoering is the repository close to being ready for creating a first release? I can add a preferred citation if you want, just need to know the authors.

**Comment by peterdesmet** [comment]
@mdoering, I noticed there was a citation in the README. I have updated it to reflect the standard preferred citation. 

From:

> Renato De Giovanni, Markus Döring, Anton Güntsch, Dave Vieglais, Donald Hobern, Javier de la Torre, John Wieczorek, Robert Gales, Roger Hyam, Stanley Blum, Steven Perry. 2010. TDWG Access Protocol for Information Retrieval (TAPIR), Release 1.0, 2009-09-09. http://www.tdwg.org/standards/449

To:

> De Giovanni Renato, Döring Markus, Güntsch Anton, Vieglais Dave, Hobern Donald, de la Torre Javier, Wieczorek John, Gales Robert, Hyam Roger, Blum Stanley, Perry Steven. 2010. TDWG Access Protocol for Information Retrieval (TAPIR), Version 1.0. Biodiversity Information Standards (TDWG) http://www.tdwg.org/standards/449

**Comment by peterdesmet** [comment]
@mdoering, where are we on the last remaining checks?
- Describing migration in an issue at https://github.com/tdwg/tapir/issues: something you could do, if you deem it necessary
- Create a release: I think that is planned in https://github.com/tdwg/tapir/issues/4 ?
- Invite relevant people. The team @tapir currently has you and Renato, which I think is a good start.

So, ok if I close this issue?

**Comment by tapir** [comment]
I'm wrongly tagged on this issue. I'm not related to the "tdwg/tapir" project.

**Comment by peterdesmet** [comment]
@tapir, apologies, I meant @tdwg/tapir

**Comment by peterdesmet** [comment]
@mdoering created a release (https://github.com/tdwg/tapir/issues/4) and the repo is in the hands of the @tdwg/tapir team, so I consider this issue closed.
