### ISSUE TITLE
Find Florence uploaded presentations

### ISSUE THREAD

**Issue by CynthiaParr-USDA** [tdwg/infrastructure#51]
They have gotten lost in the migration

**Comment by pmergen** [comment]
There was an issue last year that the Swedish presentations from 2014 would falsely upload in the 2013 Florence slot. Not sure how it was solved in the end but this may have caused a bug with the Florence presentations during the migration.

**Comment by sblum** [comment]
The 2014 presentations (Jonkiping) have been restored to the "slides upload" section of the 2014 meeting.  I looked at about 6 presentations and all looked like they were from 2014, so I don't thing there was mixing with the 2013 meeting.

The entire 2013 meeting got lost in the migration.  The meeting page(s) and uploaded files do exist on the ww1.tdwg.org.  I am working on restoring these.

**Comment by peterdesmet** [comment]
I noticed the 2013 conference is listed under `Biodiversity Information Projects of the World` in the left-hand menu: http://www.tdwg.org/biodiv-projects/2013-conference/ So, it's still there, but at the wrong place (notice also the URL).

**Comment by sblum** [comment]
Excellent catch, Peter!  I've corrected this and moved it back to where it belongs.  Also, checked pages and content of uploaded files.  The files I checked are from the Florence meeting, not Jonkiping.  Closing this issue.
