### ISSUE TITLE
Migrate mailmain to new server / VH

### ISSUE THREAD

**Issue by timrobertson100** [tdwg/infrastructure#53]
Mailman resides on the "old" TDWG servers (i.e. the ones we are migrating from and will be powered down as soon as reasonable). 

This should be migrated to a new VH on GBIF (CentOS 7), with the installation documented properly on the GBIF server wikis.

This is to be done _after_ the conference traffic dies down.

**Comment by peterdesmet** [comment]
@mdoering, is this something you can pick up?

**Comment by mdoering** [comment]
Yes, the week after TDWG sounds good. Some setup questions:
- do we want to also continue with the postfix aliases or are these handled now by MailChimp? These are all the tdwg roles and committees, e.g. chairman@tdwg.org, secretary@tdwg.org, exec@tdwg.org
- we keep the current 4 lists: tdwg, tdwg-content, tdwg-phylo, tdwg-tag
  http://lists.tdwg.org/mailman/admin
- what should happen with the archives of the old lists such as tdwg-sdd or tapir? I dont think they are exposed anywhere right now. As a start I would just copy the archive files

**Comment by mdoering** [comment]
How about we move the larger postfix lists (conference, xcom, convener) to mailman and make the others backed by a simple mysql table which we can modify through mysql admin

**Comment by peterdesmet** [comment]
@mdoering I'll let others ping in if this is a good way forward. Do you need @tdwg/exec decision on this?

**Comment by mdoering** [comment]
@peterdesmet could you discuss in @tdwg/exec please what to do with the postfix aliases? I think we should move to something more maintainable than the postfix config files for those small groups, dont you think? maybe also just mailman? I think that'll be my favorite

**Comment by peterdesmet** [comment]
What are (the) postfix aliases exactly? Not familiar with these things and I assume neither is the exec.

**Comment by mdoering** [comment]
we use the following [postfix aliases](https://github.com/tdwg/infrastructure/files/42917/virtual.txt), most importantly the ones listed above chairman, convener, secretary, exec and xcom@tdwg.org

The current mailman lives on lists.tdwg.org 
I assume we keep using that domain for the new list server and update the virtual host at https://github.com/tdwg/infrastructure/blob/master/vhosts/lists.tdwg.org.conf

**Comment by sblum** [comment]
Maintaining the postfix alias file is not difficult, if you have login access to server and some very simple instructions (thanks Markus!).  The main benefit of moving the longer lists to mailman would be the spam filter that gets applied to those lists.  The alias for the exec gets a little bit of spam.  I don't think either of these are big issues.

Markus, If you want to set up maintenance of the other aliases in MySQL, that might be helpful, but I don't think the motivation to switch away from the postfix file is that high.  So I would say do it ONLY if it's very easy.

**Comment by mdoering** [comment]
well, the aliases do not change that often also so I think I keep things as they were then. At least for now.

Should we apply some cleaning to the [file](https://github.com/tdwg/infrastructure/files/42917/virtual.txt)? Looks to me we can remove the personal TIP member aliases at least

**Comment by sblum** [comment]
I'm tasked with adding the new members of the executive committee, but we are also just starting a run-off election to determine the final member of the exec.  (There was a tie.)  I can do the clean up then.   Thanks.   Installation and configuration of the software on the new server are the things that you are more uniquely qualified for ;-)

**Comment by peterdesmet** [comment]
Do we still need @tdwg/exec input for this?

**Comment by mdoering** [comment]
I think for now we don't need any further input. I will keep all mail related configs in [github](https://github.com/tdwg/infrastructure/tree/master/mail)

**Comment by mdoering** [comment]
@sblum could you look at the latest [virtual](https://github.com/tdwg/infrastructure/blob/master/mail/postfix/virtual) file please? I'm keeping all configs in the github repository, so it would be nice if you could do changes in github first and then pull them on the server (in roots home) so they become available

**Comment by sblum** [comment]
This file is now updated for 2016.  See updates listed in commit
description.

-Stan

**Comment by mdoering** [comment]
mailman, postifx and apache VH lists.tdwg.org are migrated to the new machine

**Comment by mdoering** [comment]
postfix and mailman have been stopped on owl
