### ISSUE TITLE
Ask github for a free account

### ISSUE THREAD

**Issue by timrobertson100** [tdwg/infrastructure#54]
The nature of TDWG doesn't quite meet the requirements for [non profit](https://github.com/nonprofit) as TDWG are not _yet_ registered officially as non profit.  Regardless of this, the nature of TDWG and the cause is likely to align with the intention behind github supporting free github accounts.  We should approach github and ask for a waiver of fees TDWG ($25 / month)

**Comment by stanblum** [comment]
I wrote to them Friday and got a reply this morning (Sat).  They have temporarily given us a  free account, for 9 months.  If we haven't received our IRS determination by then, they will re-evaluate the situation.  As soon as we get our status approved, we need to send them a copy of the letter from the IRS.  They also refunded the $25 monthly fee we paid for April. ( Bonus ! )
