### ISSUE TITLE
Ensure appropriate back up procedures for server at GBIF

### ISSUE THREAD

**Issue by CynthiaParr-USDA** [tdwg/infrastructure#57]
All content managed on GBIF server(s) should have a back up on a regular basis -- not necessarily every day but perhaps once a week.

**Comment by pmergen** [comment]
It depends what is on the back up server. and the risk of what could be lost versus the workload. Some days when we prepare the conference or when we are ratifying a new standard, lot can be added and lost within a week, while other periods are calmer.  Would need to be discussed with GBIF admin how much workload/ disc space this would cost versus risk of loosing data, if it is incremental backup or a full back with replacing former versions etc . if it is more more work for them to be flexible about it or better a routine that is the same regular basis (from experience the latter is often preferred).

**Comment by sblum** [comment]
I had an exchange with Andrei around the time of the meeting.  He said they were doing nightly incrementals, and full back ups on weekends, but I believe he is also leaving GBIF, so I need to review procedures with the new head of Sys admin (or whomever Tim designates to be in charge of our backups).

**Comment by MattBlissett** [comment]
I reviewed the backup procedures after taking over the systems administration, and left them as Andrei described:
- A backup to a hard disc pool is taken every night (full once per week, incremental each other day)
- A full backup to tape is taken every two weeks.

Tapes are stored in a fireproof safe, some are recycled, but at least one from every 6 months is kept for five years.  The hard disc pool continually drops the oldest daily backup as space is used, at the moment the oldest daily backup is from 25 June.

This is the same for GBIF and TDWG servers.

**Comment by CynthiaParr-USDA** [comment]
Thank you for the clear explanation. Recommend that this be captured in a wiki page where it will be easy to find. I have added to the wiki under "Back up procedures"

**Comment by MattBlissett** [comment]
I've updated the wikipage to reflect changes to the backup procedures at GBIF (migration to Copenhagen University system).
