### ISSUE TITLE
Migrate rs.tdwg.org 

### ISSUE THREAD

**Issue by mdoering** [tdwg/infrastructure#59]
rs.tdwg.org is used for technical resources of various standards. It serves (xml) schemas, the ontology rdf files and many other important files. The current definition can be found at https://github.com/tdwg/infrastructure/blob/master/vhosts/rs.tdwg.org.conf

The current setup relies on a tdwg run svn repository for some standards (e.g. tapir, ncd), while other have already setup redirects to github or google code (e.g. dwc, ontology).

Update the virtual host file for rs.tdwg.org to serve all content strictly from github and when complete  serve it from tdwgng, switching off the old host

**Comment by CynthiaParr-USDA** [comment]
It looks like all that is left here are rewrites. So I am taking off the blocks-old-server tag.

**Comment by mdoering** [comment]
Cindy, I would prefer to leave all the blocks old server tags. It is now hard to fine the relevant issues. Getting all the rewrites done properly isn't that simple and blocking a shutdown of owl.

I will try to look after the ontology one. Maybe we can then just serve rs.tdwg.org from the new machine and fix any missing redirects we have overseen when people complain? The currently existing redirects for rs.tdwg are here: https://github.com/tdwg/infrastructure/blob/master/vhosts/rs.tdwg.org.conf

**Comment by mdoering** [comment]
I have archived the current content of the rs.tdwg.org apache documents at https://github.com/tdwg/infrastructure/tree/master/rs.tdwg.org

This is a crude mix of various SVN repository checkouts and none of the files should have been managed on the server. Most of them are in fact already on respective github repos, but not all and potentially in slightly different versions, so I think its best to archive the current snapshot.

**Comment by CynthiaParr-USDA** [comment]
Okay, I'll try to put the tags back @mdoering -- please close the tickets when you think they are done.

**Comment by mdoering** [comment]
served from tdwgng now
