### ISSUE TITLE
Migrate "Access to Biological Collection Data - version 2.06"

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/infrastructure#6]
Current URL: http://www.tdwg.org/standards/115/
- [x] Contact someone from the standard task group
- [x] Verify the standard is not maintained in another repository already
- [x] Decide on shortname: `abcd`
- [x] Ask for preferred citation
- [x] Create repository
- [x] Create a README based on the standard abstract
- [x] Download the standard and move the content to GitHub.
- [x] Create managing team
- [x] Invite all relevant people to the team managing the standard on GitHub.
- [x] Describe migration in an issue
- [x] Create a release
- [x] Document URL redirect

**Comment by mdoering** [comment]
I have spoken to Mareike Hirschfeld last week who is part of the just started ABCD3 project. They start by cleaning up existing ABCD documentation floating around and I have proposed her to do this by migrating ABCD to github and use the repos wiki to document it as best as they can.

Shall I ask Walter, Anton and Mareike (Mareike.Hirschfeld@mfn-berlin.de) to lead this?

**Comment by peterdesmet** [comment]
Yes please. Can I already create a repo and move the old standard there (so the migration is done at least)?

**Comment by mdoering** [comment]
yes please

**Comment by peterdesmet** [comment]
Repo has been created at https://github.com/tdwg/abcd, with abstract in README and download file (a single html file called `ABCD_v206.html`) dropped in the root. No other content to be migrated from http://www.tdwg.org/standards/115/, but there are still other ABCD files/website floating around, that could be consolidated in this repo as well.

A team [abcd](https://github.com/orgs/tdwg/teams/abcd) with admin access has been created with @mdoering as only member.

@mdoering can you tackle the other tasks or delegate them to to Walter et al.?

**Comment by mdoering** [comment]
Contacted BGBM for expanding the team members

**Comment by peterdesmet** [comment]
Release created at https://github.com/tdwg/abcd/releases/tag/2.06
