### ISSUE TITLE
forgot password functionality in the membership resulting in page not found error

### ISSUE THREAD

**Issue by AaronWilton** [tdwg/infrastructure#65]
![tdwg forgot password 1](https://cloud.githubusercontent.com/assets/9813877/13129155/dddec684-d63f-11e5-896b-fad0d68f27ed.jpg)
![tdwg forgot password 2](https://cloud.githubusercontent.com/assets/9813877/13129154/ddde5bc2-d63f-11e5-85b2-410a67d9682a.jpg)

**Comment by peterdesmet** [comment]
@sblum, any idea on how to solve this?

**Comment by stanblum** [comment]
Unfortunately, not yet, but William and I are trying to wrap our heads
around Typo3 and Typoscript.  We have made some progress with other
lingering issues, so I do have hope.  (Need to find where that link is
stored and then change it to the page that does work for resetting a user's
password.)

**Comment by WUlate** [comment]
Solved!

**Comment by stanblum** [comment]
Thanks, William!
