### ISSUE TITLE
Shutdown owl.tdwg.org server

### ISSUE THREAD

**Issue by mdoering** [tdwg/infrastructure#66]
We like to shutdown the prehistoric owl tdwg machine at GBIF. It serves varies things at the moment, some of which have been migrated already to a newer setup:
- [x] mailman & http://lists.tdwg.org
- [x] TWiki at http://wiki.tdwg.org/
- [x] http://rs.tdwg.org exposing the SVN & static content
- [x] http://lsid.tdwg.org
- [x] http://tapir.tdwg.org
- Mailman has been migrated: #53
- The wiki should be moved and archived at github: #62, #16
- rs.tdwg.org hosts various resources, some of which have been migrated already. Propose to archive the SVNs somewhere, as github repos if possible. #59, #33
- lsid is dysfunctional and can be shutdown? #60
- tapir.tdwg.org does not seem to be used: tdwg/tapir#5

**Comment by mdoering** [comment]
LSID setup from owl archived in this repo: https://github.com/tdwg/infrastructure/commit/8d2bfef749d5d050ef3579df9b6800717275321d

**Comment by stanblum** [comment]
We talked many months ago about crawling the twiki site.  I haven't done
that, as I'm not sure how to test the results as an effective archive --
something that would enable us to at least read all of the content.  If we
ran a typical wget job, where would we put the results?  Also, the twiki
site itself seems to be effectively unusable.  Any ideas?

**Comment by mdoering** [comment]
I have copied the entire twiki installation into this github repo: https://github.com/tdwg/wiki-archive
So all data is preserved and we can shutdown the wiki cause it is dysfuncitonal anyways as you say

**Comment by mdoering** [comment]
TAPIR can be shutdown as we have another instance of the tools running at sourceforge, see tdwg/tapir#5

**Comment by CynthiaParr-USDA** [comment]
As soon as this is shut down please close the ticket.

The rs.tdwg.org rewrites are already ticketed in https://github.com/tdwg/ontology/issues/  .  Assigning to @timrobertson100 who can reassign as necessary.

**Comment by mdoering** [comment]
The rs.tdwg.org rewrite rules are dealt with in ticket #59, the ontology one is just one piece of it

**Comment by MattBlissett** [comment]
I have shut down `owl.tdwg.org` / `192.38.28.106`, also last known as `lsid.tdwg.org` and `tapir.tdwg.org`.

Dumps of the filesystems are on `tdwgng`, in the `/root/owl-backup` directory.  These ones compressed very well, so aren't anywhere near as large as `falcon`'s.

```
1.2G Mar 17 10:30 root-fs.tar.xz
746M Mar 17 10:55 var-www-fs.tar.xz
```

**Comment by timrobertson100** [comment]
Thanks everyone!
