### ISSUE TITLE
Move DNS for TDWG.org to a cloud provider

### ISSUE THREAD

**Issue by MattBlissett** [tdwg/infrastructure#67]
Hi,

We're planning on moving the DNS for GBIF.org (and our other domains) to a cloud provider, probably Amazon Route 53.  This should provide faster DNS lookups since Amazon have servers around the world, and simplify maintenance — upgrading DNS server software is a chore.

Can we do the same with TDWG.org?

**Comment by stanblum** [comment]
Yes, I think that would be fine with us.  Would there be a cost associated
with that, or is it small enough that it would not be worth the hassle to
share it?

Also, please note that I think my former institution (calacademy.org) was
running a GBIFDNSmirror on their stack of virtual servers.  We should tell
them that this can be decommissioned, if/when that happens.

**Comment by MattBlissett** [comment]
Thanks.  I think the cost is so small it won't be worth the administration, we expect it to be something like $6 per year.

The Natural History Museum (London) is hosting a DNS mirror for TDWG.  I'll let them know once we've moved and thoroughly tested everything.

(Calacademy.org is already using Amazon DNS. How's that for a recommendation? :-) )

**Comment by MattBlissett** [comment]
Hi Stan,

We've moved GBIF.org's DNS to Amazon, and all looks to be working fine.  It's much faster for users outside Europe, and a little faster for users in Europe but not in Denmark.

Since you are the technical administrator for the tdwg.org domain, please could you update the name servers as follows:

```
ns-1521.awsdns-62.org.
ns-2002.awsdns-58.co.uk.
ns-112.awsdns-14.com.
ns-954.awsdns-55.net.
```

If you let me know when it's done, I'll check everything is working correctly.  I don't expect any interruption of service; we had no issues moving GBIF.org.

Thanks.

**Comment by stanblum** [comment]
Hi Matt,

I've entered the addresses above as our DNS servers for tdwg.org.

We also have "LSID.info" as a domain name we serve.  It is currently (not changed yet) pointing to the same servers we had used for tdwg.org; i.e., NS.TDWG.GBIF.ORG and MAILSERVER.NHM.AC.UK.   Do you still have entries for that in your DNS?  and can I go ahead and update the DNS servers for LSID.info?

**Comment by mdoering** [comment]
If we want to server the lsid domain still the tdwg apache virtual host must be reactivated and fixed, see #60

**Comment by stanblum** [comment]
Did you see Rod Page's tweet yesterday:

_Roderic Page_ ‏@rdmpage  https://twitter.com/rdmpage Mar 8
https://twitter.com/rdmpage/status/707195746823643139Glasgow, Scotland
https://twitter.com/search?q=place%3A791e00bcadc4615f

Hey @tdwg https://twitter.com/tdwg what happened to the LSID resolver
http://lsid.tdwg.org  https://t.co/47pxH8qBkH ? Is this the death of
LSIDs?

Was it really broken?  While I would like LSIDs to be deprecated, it would
be good to phase them out after giving clear notice and direction to a
better alternative.  On the other hand, if it needs to be fixed, I probably
don't have the skills to fix it.  Would appreciate your thoughts.  I will
look at the code in this repository later today.

**Comment by rdmpage** [comment]
http://lsid.tdwg.org looks like this:
![lsid](https://cloud.githubusercontent.com/assets/83306/13649097/d2a0e4d8-e633-11e5-990b-0519232cdd51.png)
I'd be sorry to see LSIDs go, simply because for a key class of data (taxonomic names) just about everybody uses them to serve RDF in a consistent format. It's one of the few success stories in the field but we managed to turn victory into defeat by not actually doing anything with the resulting RDF :( Something of a missed opportunity...

Anyway, it would be useful if http://lsid.tdwg.org was resurrected...

**Comment by stanblum** [comment]
Thanks for the feedback, Rod.

Does anyone else have an LSID resolver running that we could point to
instead, or is the only way to keep lsids functioning to restore the one on
the tdwg domain?

**Comment by rdmpage** [comment]
I'm not aware of another public LSID resolver. I have a tester at http://darwin.zoology.gla.ac.uk/~rpage/lsid but that's not set up as a simple resolver. Given that the TDWG resolver is mentioned in TDWG documents, e.g. https://raw.githubusercontent.com/tdwg/guid-as/master/lsid/applicability_statement.doc should TDWG support the resolver? Maybe something like a Docker image could be created to make this service self-contained and easier to maintain.

**Comment by timrobertson100** [comment]
Please continue the LSID discussion on the LSID ticket https://github.com/tdwg/infrastructure/issues/60 as the decision to run LSID is unrelated to the location of the DNS server.

**Comment by MattBlissett** [comment]
> because for a key class of data (taxonomic names) just about everybody uses them to serve RDF in a consistent format

Do they? The two example LSIDs on your tester don't resolve.  I think we (Markus or I) should find the logs for the TDWG resolver and see if anyone was actually using it, and not just for curiosity's sake.

### Broken LSIDs
* urn:lsid:algaebase.org:taxname:101541
* urn:lsid:biodiversity.org.au:afd.name:433239
* urn:lsid:catalogueoflife.org:taxon:d242422d-2dc5-11e0-98c6-2ce70255a436:col20130401
* urn:lsid:faunaeur.org:taxname:247005
* urn:lsid:fishdb.sinica.edu.tw:collection:NMMBP03358
* urn:lsid:gdb.org:GenomicSegment:GDB132938
* urn:lsid:indexfungorum.org:names:319089
* urn:lsid:ipni.org:names:20012728-1:1.1
* urn:lsid:ncbi.nlm.nig.gov:GenBank:T48601:2
* urn:lsid:ncbi.nlm.nih.gov:pubmed:12571434
* urn:lsid:perlegen.hapmap.org:Assay:25760.7590602:1
* urn:lsid:pseudogene.org:9598.Pseudogene:21
* urn:lsid:ubio.org:namebank:11815
* urn:lsid:zoobank.org:act:8BDC0735-FEA4-4298-83FA-D04F67C3FBEC

### Working LSIDs
* urn:lsid:biosci.ohio-state.edu:osuc_pubs:229
* urn:lsid:itis.gov:itis_tsn:180543
* urn:lsid:marinespecies.org:taxname:138474
* urn:lsid:nmbe.ch:spidersp:021946

**Comment by MattBlissett** [comment]
I'm closing this, since tdwg.org is correctly migrated to Amazon — thanks, Stan.

lsid.info isn't doing anything at present. I'm not sure it was doing anything before — it points to a different IP than lsid.tdwg.org.

If TDWG decide to run something using the domain we can change its DNS too.
