### ISSUE TITLE
Shutdown falcon.gbif.org (URGENT!)

### ISSUE THREAD

**Issue by timrobertson100** [tdwg/infrastructure#68]
It is now becoming **urgent** that TDWG start switching off old machines as the university network folks are again alerting vulnerabilities.  This impacts GBIF position on the network and so we need to take this with some seriousness.  It is possible at some point we will have to switch them off or risk going offline.

On falcon.tdwg.org there is the LSID site, MySQL, and LDAP and some other Virtual Hosts.

Is this part of the "new" TDWG site?  

@csparr - Could I please ask if it is ok that you coordinate some decisions on legacy systems, such as LSID resolving etc which remain open?

(ETA: This is a RedHat 4 (!!!) u9 server and the issue is OpenSSL)

**Comment by jmacklin** [comment]
Thanks, Tim.

@csparr maybe we should have a separate meeting on this issue involving
those interested on the EX with stakeholders. The recent LSID discussion
will require some deeper consideration or a stopgap of some kind to allow
Tim to deal with his issues (which I can certainly relate to ;-).

James

**Comment by CynthiaParr-USDA** [comment]
Yes, we could have an urgent meeting. LSID resolving seems to be the most
serious and we will need to talk about it.  Sorry I wasn't paying attention
to https://github.com/tdwg/infrastructure/issues/60 but I appreciate Rod's
offer to help.

Stay tuned for meeting coordination.

Cyndy

**Comment by jmacklin** [comment]
I assume we have an agreement with GBIF on patching and maintenance at the
server/OS level but what about our apps? If we are responsible then we need
a game plan. OS patching can influence apps...

James

**Comment by CynthiaParr-USDA** [comment]
I think the understanding when we paid for a new server was that we would not expect GBIF to patch and maintain the old server. So we do need a game plan.  Almost everything is probably off that server (including some of the tickets referenced here: https://github.com/tdwg/infrastructure/labels/blocks-old-server-switchoff)

**Comment by stanblum** [comment]
[this note also posted to slack/tdwg-tech]  I have a wget crawl of OJS, but haven’t checked it thoroughly  for completeness (a directory tree with MANY branches).  Also, and perhaps more usable is the MySQL db that held the content under OJS.  That is already migrated over to the current server under our website (tdwgng:107).  The table structure looks pretty sensible.  It contains titles, authors, abstracts, etc., but those tables don’t contain marked-up html, just simple text.  But all of the OJS code has also been migrated to the new server, so it’s accessible without the old server. /var/www/ojs/.  I think falcon can go down.

**Comment by stanblum** [comment]
I think Falcon can go down.

**Comment by CynthiaParr-USDA** [comment]
Agree.  Time to shut it down. Please close the ticket when that is completed.  Assigning to @timrobertson100 who can reassign as necessary.

**Comment by CynthiaParr-USDA** [comment]
Is there any archive of the pages from http://www.lsid.info ? There's a reference to code on sourceforge but that's dead.

Can any of this be archived?

**Comment by MattBlissett** [comment]
There's a DNS configuration problem (I think that's my fault) with http://www.lsid.info, or possibly the site hasn't worked for a long time — there's nothing useful in the Wayback Machine.

There is perhaps just a single page.  I've temporarily copied it [here](http://bitbucket.matt.blissett.me.uk/www.lsid.info/) so you can see.  It's produced by Typo3, but could easily be put somewhere as a static page if needed.

The Sourceforge site is working fine: https://sourceforge.net/projects/lsids/

**Comment by MattBlissett** [comment]
Thanks everyone.

`falcon.tdwg.org`, `192.38.28.103`, is now shut down.

In case it helps people find where the server has gone, it also had the DNS names `tdwg2006.tdwg.org`, `gaiaresources.lsid.tdwg.org`, `ww1.tdwg.org`, `falcon.tdwg.gbif.org` and `www.lsid.info`.

A filesystem backup is on tdwgng.tdwg.org in `/root/falcon-backup`, in case anything needs to be recovered.  It's large (12GB) so there won't be space for it on that server forever.

```
 288 Mar 17 06:45 README
1.1G Mar 17 05:21 root-fs.tar.xz
347M Mar 17 05:23 usr-fs.tar.xz
107M Mar 17 06:41 var-fs.tar.xz
821M Mar 17 05:34 var-lib-mysql-fs.tar.xz
9.0G Mar 17 06:28 var-www-fs.tar.xz
```

I can't close the ticket, someone else will need to press the button.

**Comment by timrobertson100** [comment]
Sincere thanks to everybody involved for making this happen so quickly.
