### ISSUE TITLE
Post messages alerting community to status of certain resources

### ISSUE THREAD

**Issue by CynthiaParr-USDA** [tdwg/infrastructure#69]
In order to alert stakeholders, need to develop and post messages about availability (or lack thereof) going forward of:
-  lsid server
- rs.tdwg.org
- ojs
- wiki

Should be posted to 
- [ ] tdwg.org website
- [ ] TDWG-content mailing list.

**Comment by CynthiaParr-USDA** [comment]
I'm worried this is going to get lost, but I don't feel I can write the letter.  Assigning to Tim, but if you want Stan or I can send it out if you draft it.

**Comment by stanblum** [comment]
Tim, I can help with that.  Will try to write a draft later today (after you've gone to bed ;-)   Look for it in the AM.

**Comment by MattBlissett** [comment]
Can this be closed?  I think the tasks have been completed (whether or not the community was informed).
