### ISSUE TITLE
Migrate "Structured Descriptive Data"

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/infrastructure#7]
Current URL: http://www.tdwg.org/standards/116/
- [x] Contact someone from the standard task group
- [x] Verify the standard is not maintained in another repository already
- [x] Decide on shortname: `sdd`
- [x] Ask for preferred citation
- [x] Create repository
- [x] Create a README based on the standard abstract
- [x] Download the standard and move the content to GitHub.
- [x] Create managing team
- [x] Invite all relevant people to the team managing the standard on GitHub.
- [x] Describe migration in an issue: https://github.com/tdwg/sdd/issues/1
- [x] Create a release
- [x] Document URL redirect

**Comment by peterdesmet** [comment]
@tdwg/infrastructure, who should I contact for this?

**Comment by CynthiaParr-USDA** [comment]
Try Gregor Hagedorn - gregor.hagedorn@mfn-berlin.de

**Comment by peterdesmet** [comment]
Contacted.

**Comment by peterdesmet** [comment]
Release created at https://github.com/tdwg/sdd/archive/master.zip
