### ISSUE TITLE
Shutdown of tdwgbox.tdwg.org

### ISSUE THREAD

**Issue by MattBlissett** [tdwg/infrastructure#71]
`tdwgbox.tdwg.org` / `192.38.28.102` is the final TDWG server doing almost nothing.

It has the following hostnames pointing to it:
- `biogeosdi.dev.tdwg.org`
- `biogeosdi.tdwg.org`
- `roger.dev.tdwg.org`
- `tapirtester.dev.tdwg.org`
- `www.dev.tdwg.org`

It used also to serve `www.biocol.org`, but I see that is now elsewhere.

Can this be shut down? It looks like these hostnames were only for development, and needn't be maintained.

There's also an empty MySQL server.

**Comment by stanblum** [comment]
That was probably the first testing platform for the TIP team (TDWG Infrastructure Project - 2005-2007).  Yes, it can be shutdown.

**Comment by MattBlissett** [comment]
Thanks Stan.

I've shut it down.
