### ISSUE TITLE
http://tdwg.org to be handled by www.tdwg.org

### ISSUE THREAD

**Issue by stanblum** [tdwg/infrastructure#72]
Several people have noticed that http://tdwg.org gives a blank directory listing; it doesn't get handled by Typo3 and produce the www.tdwg.org home page.  This is odd because Typo3's configuration includes accepting requests to unqualified "tdwg.org".  Is there something that should be added to the apache config or vhosts?

Also note that my chrome browser was automatically forwarding me from tdwg.org to www.tdwg.org.  I could only see the directory listing (empty) when I used Firefox.

**Comment by MattBlissett** [comment]
Apache wasn't handling tdwg.org, it was falling through to http://rs.tdwg.org instead (should that page be something other than an empty directory listing?)

I've set tdwg.org to redirect to www.tdwg.org, as I understand that's better for search engines.
