### ISSUE TITLE
Invasive Species Interest Group member list

### ISSUE THREAD

**Issue by mdoering** [tdwg/infrastructure#73]
The Invasive Species Interest Group has a member list that has not been used in a very long time. 
Annie Simpson used to be an administrator of the interest group member list but can no longer access it (only the first page) at its previous location: http://www.tdwg.org/activities/invasives/members/

Has that member list been maintained in typo3 and now vanished? Can it be resurrected?

**Comment by stanblum** [comment]
I think interest/task group member lists are managed by
"self-subscription".  A user can update his/her profile by adding and
removing which interest/task groups are selected there.  I don't think a
convener could ever add or remove another person's interest.

But perhaps more to the point, what does Annie want to do with this list?
I don't think there are any functions based on these lists.  If should
would like to email them all, I might be able to help with that.  I'll ask.

And by the way, I could page through the member list without being logged
in.  I didn't see anyway to maintain the list, though there is a mention on
the page about group conveners being able to do that.  (More content to be
edited given our reduced functionality.)

**Comment by stanblum** [comment]
I sent a list of Interest group members (users who self identified as interested in Inv Spp) and their emails  to Annie Simpson.
