### ISSUE TITLE
Complete rollout for the Standards Document Implementation

### ISSUE THREAD

**Issue by timrobertson100** [tdwg/infrastructure#93]
Action items:

- [x] Determine which of the standards landing pages are already adequate and don't change them.
- [x] Determine which landing pages have content that needs to be kept but need to have descriptions of and links to their standards documents.
- [x] Use the landing pages I've generated by script for the standards whose landing pages aren't adequate or that don't exist at all.
- [x] Create links to the new landing pages on the TDWG standards page https://www.tdwg.org/standards/.
- [x] Fix the redirects for all of the standards IRIs (in the form http://www.tdwg.org/standards/116) so that they point to the standards landing pages and not to something else like a Github repo or a particular standards document.

**Comment by baskaufs** [comment]
[This issue](https://github.com/tdwg/website/issues/129) can be dealt with in this review.

**Comment by baskaufs** [comment]
Also 
- [build XDF page](https://github.com/tdwg/website/issues/125)
- [IH page](https://github.com/tdwg/website/issues/126)
- [PNDB](https://github.com/tdwg/website/issues/124)
- [Floristic Regions](https://github.com/tdwg/website/issues/123)
- [BPH](https://github.com/tdwg/website/issues/121)

**Comment by baskaufs** [comment]
Related [Standards URI redirection issue](https://github.com/tdwg/website/issues/83)

**Comment by baskaufs** [comment]
Close [this issue](https://github.com/tdwg/website/issues/46) when finished.

**Comment by baskaufs** [comment]
I see that I created a [milestone](https://github.com/tdwg/rs.tdwg.org/milestone/1) for this a while ago. it should be reviewed before closing this issue.

**Comment by baskaufs** [comment]
There is nothing blocking completion of this other than somebody just doing it. Refer to https://github.com/tdwg/ac/issues/232#issuecomment-1036338939 for details.

**Comment by baskaufs** [comment]
Everything seems to be done here now.
