### ISSUE TITLE
adjust IP for terms.tdwg.org subdomain

### ISSUE THREAD

**Issue by DavidFichtmueller** [tdwg/infrastructure#98]
After some long delays, the Biowikifarm is back online but on a new public IP: 212.201.100.126 . The subdomain terms.tdwg.org needs to be adjusted, so it points to the TDWG Terms Wiki. The BWF is far from fully functional, for the wikis I was able to take a look at, it is in read-only mode and with css issues, but at least the main content of the pages is rendered again. As there are still some links that point to the server for some term definitions etc, it could still be useful for some people who might stumble upon those outdated links.

**Comment by MattBlissett** [comment]
Done, though I only see a "Welcome to nginx" page at http://terms.tdwg.org/

**Comment by DavidFichtmueller** [comment]
Thank you Matt, for the quick update. I will relay this to Falko Glöckler, as he is the person in charge. Could be, that there is still some configuration file missing or something.

**Comment by DavidFichtmueller** [comment]
As I assumed, it was a configuration issue. The final steps of the configuration could only be done, after domain was working properly. It has been fixed now and the wiki is up again (with some of the other issues I mentioned this morning also having been resolved now).

**Comment by stanblum** [comment]
Hi @DavidFichtmueller,  I tried to check if any of the terms.tdwg.org resources were available.  I wasn't able to find anything by browsing or searching.  Is anyone planning to do more to try to make the terms.tdwg.org server more functional?  TDWG would still love to get full dumps of the GGBN terms and the EFG terms.
